apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: harvester-longhorn
  name: cirros-default-image
  labels:
    harvesterhci.io/image-type: raw_qcow2
    harvesterhci.io/imageDisplayName: cirros
  namespace: default
spec:
  checksum: ""
  displayName: cirros
  pvcName: ""
  pvcNamespace: ""
  retry: 3
  sourceType: download
  storageClassParameters:
    migratable: "true"
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
  url: http://192.168.9.163:5000/cirros-0.5.1-x86_64-disk.img
