apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: opensuse-vm-workloads
  namespace: fleet-local
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - "/vm-workload"
  pollingInterval: 300s
  repo: https://github.com/irishgordo/harvester-fleet-demo
  targetNamespace: default
  targets:
    - clusterSelector: {}
