apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: ssh-access-node-1-only
  namespace: default
spec:
  matchSelector:
    vmnode: harvester-node-1
  filename: 99_ssh_node_1_only.yaml
  contents: |
    stages:
      network:
        - authorized_keys:
            rancher:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHYl9ZFAxCTCQDVw+ngsWQu8Jo0LhmSF5KFh+G8Qxt67