apiVersion: harvesterhci.io/v1beta1
kind: KeyPair
metadata:
  name: vm-workload-keys
  namespace: default
spec:
  publicKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCksKyQcOefu3yOGiUYgwCkVQiTcfd0ZXy78F3eT8Iyu54VtAiKqTuvSQwptszexifMumIXg5H2hL8aBy0/3szr2jGY6kvU0pR5s2TWqbmOJWd+jZqfYXiYT69sXqQUvqvSPLlliOGgBA2Uj/wvQ1y1INbYO/8K5CmPick7j0eSfA2qCXtwyOy8frWMnyD6hPI0Hy52FHtG5Mbh2t4YpftyZJcNPh6tszO2o+9jGC7pndgqsIUlifKuGN84GbEX2YeK6nNALO7g39pKQHceENJST2qoIRO7SoQOCLLUWXS+d4sPs76uOIiKikUvJeSn1gF44FPPvU+bCm+usRgj+XyKgu2lyrLnb4bYSX+pvw1i8y/DTy60L6lLco0w2XpxRiTOD8PZtBWQD2vowjqOUuk4m/nDX1tltWl/IdOtlnplwmgGsMOw9cWP9QIbKBsAWzmqqGBAREEnK1vX1oof/tUA+NW6H/ubcMD6rcsOQydLuCYXsCSYB5j7WuqSr1AMFAU5+jsUyDVPxnqk+uz8HCOdrmlYAWGcn+tw6tUPQEhAm/BAGOPNNTEU5LrimHfSPGFvvVAJ7JqwTkxnMYJq8jnWdCeI51RqdQ1aU5k/H8eiqKto4sHlkODSNH6YPHeA9VvNtmaFCc2EX2DgMe5VdImyxbtthibUySDEYbv33GrlTQ==
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6ntW4lJPVoN25R8Q1BLcYHlXAAAE0z2lAszM5pI7Lb9ucz2PpnIwckpHPMl+rHmQlm0iHHQsA5jk62LY5xZhN1WPKHFdpBHQei9lbWTUTw+cGfEjFfrmrD+wRCbslCNqfZRxd/+BvbkWGBpdyfHoTA+Cr6b/lGODQWswtkYtm+3/ZVwvvzWG3yfqLFMP8yKFv8a+g+4CPZ/aWIZrDO/MQPiT94sfSXN+2EoICJkJBqriwbLk8KVIb8Bpa6Ykx2CY8x0RxfinOkrz7ic6wirdZEII27bqZ0B2RSL4wUX2xLcfdqqZ5KbUHPFOf8oMscC1ifGDjn2CjqW+DTR2+aqCv
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm michael.russell@suse.com

